[
    {
        "id": 10001,
        "name": "ウーロンの願い",
        "description": "特殊効果「追加ドロップ率UP」があるイベントで\n追加ドロップ率が85%UP(1回のみ)",
        "support_film_id": 1,
        "cost": 70,
        "level": 3,
        "open_at": "",
        "link_id": 100013,
        "root_id": 10001
    },
    {
        "id": 10002,
        "name": "孫悟空の結婚",
        "description": "バトル中「孫悟空の系譜」カテゴリの\n味方全員の気力+1、ATKとDEF20%UP",
        "support_film_id": 1,
        "cost": 200,
        "level": 3,
        "open_at": "",
        "link_id": 100023,
        "root_id": 10002
    },
    {
        "id": 10003,
        "name": "修業完了！！",
        "description": "バトル開始から4000ターンの間、\n味方全員のATKとDEF4000UP、\n会心の発動確率4%UP、\nバトル開始から4ターンの間、\n「亀仙流」カテゴリの味方全員の\n気力+1、ATKとDEF20%UP(1回のみ)",
        "support_film_id": 1,
        "cost": 70,
        "level": 2,
        "open_at": "",
        "link_id": 100032,
        "root_id": 10003
    },
    {
        "id": 10004,
        "name": "武道家の意地",
        "description": "バトル開始から3ターン目以降、\n「天下一武道会」カテゴリのキャラが\n敵かチームにいるとき、\n3ターンの間、味方全員の気力+1、\nATKとDEF10%UP(1回のみ)",
        "support_film_id": 1,
        "cost": 120,
        "level": 1,
        "open_at": "",
        "link_id": 10004,
        "root_id": 10004
    },
    {
        "id": 10005,
        "name": "筋斗雲との出会い",
        "description": "バトル開始から3ターンの間、\n「少年編」カテゴリまたは\n「ドラゴンボールを求めし者」カテゴリの\n味方全員の気力+2、ATKとDEF20%UPし、\n「師弟の絆」カテゴリを含む場合は\n更にATKとDEF10%UP(1回のみ)",
        "support_film_id": 1,
        "cost": 100,
        "level": 5,
        "open_at": "",
        "link_id": 100055,
        "root_id": 10005
    },
    {
        "id": 10006,
        "name": "初めてのともだち",
        "description": "バトル開始から3ターンの間、\n「少年・少女」または「人造人間」カテゴリの\n味方全員のATKとDEFと会心率18%UP、\nチームに「少年編」または「親友の絆」\nカテゴリの味方が2体以上いるとき\n味方全員のATKとDEF8%UP(1回のみ)",
        "support_film_id": 1,
        "cost": 120,
        "level": 5,
        "open_at": "",
        "link_id": 100065,
        "root_id": 10006
    },
    {
        "id": 10007,
        "name": "運命に導かれた再会",
        "description": "バトル中｢あの世の戦士｣\nまたは「時間制限」カテゴリの\n味方全員のATKとDEF10%UP",
        "support_film_id": 1,
        "cost": 200,
        "level": 1,
        "open_at": "",
        "link_id": 10007,
        "root_id": 10007
    },
    {
        "id": 10008,
        "name": "頭が満月！？",
        "description": "チームに「天下一武道会」カテゴリの\n味方がいるとき、\nバトル開始から2ターンの間、\n味方全員のATK22%UP、\n敵全体のATKを10%DOWN(1回のみ)",
        "support_film_id": 1,
        "cost": 120,
        "level": 1,
        "open_at": "",
        "link_id": 10008,
        "root_id": 10008
    },
    {
        "id": 20001,
        "name": "怒りのフリーザ",
        "description": "超系の敵がいるとき、2ターンの間、\n極系の味方全員のATK20%UP(1回のみ)",
        "support_film_id": 2,
        "cost": 70,
        "level": 3,
        "open_at": "",
        "link_id": 200013,
        "root_id": 20001
    },
    {
        "id": 20002,
        "name": "密かな想い",
        "description": "バトル開始から3ターンの間、\n「魔人ブウ編」または「正義の味方」カテゴリの\n味方全員の気力+3、ATKとDEF20%UP(1回のみ)",
        "support_film_id": 2,
        "cost": 120,
        "level": 5,
        "open_at": "",
        "link_id": 200025,
        "root_id": 20002
    },
    {
        "id": 20003,
        "name": "地上最強のコンビ誕生",
        "description": "バトル開始から2ターンの間、\n味方全体の気力+2(1回のみ)",
        "support_film_id": 2,
        "cost": 100,
        "level": 1,
        "open_at": "",
        "link_id": 20003,
        "root_id": 20003
    },
    {
        "id": 20004,
        "name": "超サイヤ人を超えろ！",
        "description": "バトル開始から3ターンの間、\n「純粋サイヤ人」または「混血サイヤ人」\nカテゴリの味方全員の気力+1、ATK8%UPし、\n更に「超サイヤ人」カテゴリの\n味方全員の気力+1、ATKとDEF15%UP、\nまたは「超サイヤ人2」カテゴリの\n味方全員の気力+2、ATKとDEF25%UP(1回のみ)",
        "support_film_id": 2,
        "cost": 150,
        "level": 5,
        "open_at": "",
        "link_id": 200045,
        "root_id": 20004
    },
    {
        "id": 20005,
        "name": "戦闘力530000",
        "description": "バトル中「ナメック星編」カテゴリの\n極系の味方全員のATKとDEF15%UP",
        "support_film_id": 2,
        "cost": 200,
        "level": 1,
        "open_at": "",
        "link_id": 20005,
        "root_id": 20005
    },
    {
        "id": 20006,
        "name": "怒りによって目覚めた戦士",
        "description": "バトル中「ナメック星編」カテゴリの\n超系の味方全員のATKとDEF15%UP",
        "support_film_id": 2,
        "cost": 200,
        "level": 1,
        "open_at": "",
        "link_id": 20006,
        "root_id": 20006
    },
    {
        "id": 20007,
        "name": "悟飯の涙",
        "description": "バトル開始から2ターンの間、\n「孫悟空の系譜」カテゴリの\n味方全員のATKとDEF10%UP(1回のみ)",
        "support_film_id": 2,
        "cost": 100,
        "level": 1,
        "open_at": "",
        "link_id": 20007,
        "root_id": 20007
    },
    {
        "id": 20008,
        "name": "奇妙な巡り合わせ",
        "description": "バトル開始から4ターン目、\nまたは自身のHP40%以下で\nチームに「純粋サイヤ人」カテゴリまたは\n「地球人」カテゴリの味方がいるとき、\nHPが50%回復し、2ターンの間、\n「純粋サイヤ人」カテゴリまたは\n「地球人」カテゴリの\n味方全員のATKとDEF10%UP(1回のみ)",
        "support_film_id": 2,
        "cost": 170,
        "level": 5,
        "open_at": "",
        "link_id": 200085,
        "root_id": 20008
    },
    {
        "id": 20009,
        "name": "ギニューのスーパーファイティングポーズ",
        "description": "超系の敵がいるとき、2ターンの間、\n極系の味方全員のATKとDEF10%UP(1回のみ)",
        "support_film_id": 2,
        "cost": 120,
        "level": 1,
        "open_at": "",
        "link_id": 20009,
        "root_id": 20009
    },
    {
        "id": 20011,
        "name": "過去で築いた絆",
        "description": "バトル開始から3ターンの間、\n「ベジータの系譜」または「親子の絆」カテゴリの\n味方全員の気力+1、ATKとDEF20%UP(1回のみ)",
        "support_film_id": 2,
        "cost": 100,
        "level": 5,
        "open_at": "",
        "link_id": 200115,
        "root_id": 20011
    },
    {
        "id": 20012,
        "name": "ベジータのプライド",
        "description": "バトル開始から3ターンの間、\n「心身の侵食」または「天才戦士」カテゴリの\n味方全員の気力+2、ATKとDEF25%UP(1回のみ)",
        "support_film_id": 2,
        "cost": 120,
        "level": 5,
        "open_at": "",
        "link_id": 200125,
        "root_id": 20012
    },
    {
        "id": 20013,
        "name": "クリリン驚異のパワーアップ",
        "description": "バトル開始から2ターンの間、\n「急激な成長」カテゴリの\n味方全体のATKとDEF10%UPし、\n「ナメック星編」カテゴリの\n味方全員の気力+3",
        "support_film_id": 2,
        "cost": 170,
        "level": 1,
        "open_at": "",
        "link_id": 20013,
        "root_id": 20013
    },
    {
        "id": 20014,
        "name": "セルゲーム開幕宣言",
        "description": "バトル中「人造人間/セル編」カテゴリの\n極系の味方全員のATKとDEF15%UP",
        "support_film_id": 2,
        "cost": 200,
        "level": 1,
        "open_at": "",
        "link_id": 20014,
        "root_id": 20014
    },
    {
        "id": 20015,
        "name": "ピッコロからの贈り物",
        "description": "バトル中「人造人間/セル編」カテゴリの\n超系の味方全員のATKとDEF15%UP",
        "support_film_id": 2,
        "cost": 200,
        "level": 1,
        "open_at": "",
        "link_id": 20015,
        "root_id": 20015
    },
    {
        "id": 20016,
        "name": "揺れ動く想い",
        "description": "バトル中「人造人間」\nまたは「地球人」カテゴリの\n味方全員の気力+1、ATKとDEF20%UP",
        "support_film_id": 2,
        "cost": 200,
        "level": 3,
        "open_at": "",
        "link_id": 200163,
        "root_id": 20016
    },
    {
        "id": 20017,
        "name": "孫悟空ついに到着！",
        "description": "HP59%以下で\nチームに「地球育ちの戦士」\nカテゴリの味方がいるとき、\n2ターンの間、味方全員の気力+2(1回のみ)",
        "support_film_id": 2,
        "cost": 120,
        "level": 1,
        "open_at": "",
        "link_id": 20017,
        "root_id": 20017
    },
    {
        "id": 20018,
        "name": "悟空の情け",
        "description": "バトル開始から4ターン目に、\n2ターンの間、「怒り爆発」カテゴリの\n味方全員のATKとDEF15%UPし、\nバトル開始から4ターン目以降に、\n「命運をかけた闘い」カテゴリの敵がいるとき、\n1ターンの間、味方全員の気力+2(1回のみ)",
        "support_film_id": 2,
        "cost": 120,
        "level": 1,
        "open_at": "",
        "link_id": 20018,
        "root_id": 20018
    },
    {
        "id": 20019,
        "name": "人造人間16号起動！",
        "description": "バトル開始から2ターンの間、\n「ターゲット孫悟空」カテゴリの\n味方全員のATKとDEF16%UP(1回のみ)",
        "support_film_id": 2,
        "cost": 120,
        "level": 1,
        "open_at": "",
        "link_id": 20019,
        "root_id": 20019
    },
    {
        "id": 20020,
        "name": "もっと強く！！",
        "description": "バトル中「師弟の絆」カテゴリの\n味方全員の気力+1、ATKとDEF20%UPし、\nバトル開始から7ターンの間、\n「地球育ちの戦士」カテゴリの\n味方全員の気力+1(1回のみ)",
        "support_film_id": 2,
        "cost": 200,
        "level": 3,
        "open_at": "",
        "link_id": 200203,
        "root_id": 20020
    },
    {
        "id": 20021,
        "name": "バーダックとカカロット",
        "description": "バトル開始から2ターンの間、\n「下級戦士」カテゴリの味方全員の\n気力+1、ATKとDEF10%UP(1回のみ)",
        "support_film_id": 2,
        "cost": 100,
        "level": 1,
        "open_at": "",
        "link_id": 20021,
        "root_id": 20021
    },
    {
        "id": 20022,
        "name": "逃げろ!!18号",
        "description": "バトル開始から2ターンの間、\n「人造人間/セル編」カテゴリの味方全員の\n気力+1、ATKとDEF10%UP(1回のみ)",
        "support_film_id": 2,
        "cost": 100,
        "level": 1,
        "open_at": "",
        "link_id": 20022,
        "root_id": 20022
    },
    {
        "id": 30001,
        "name": "シッポを引き出せ！",
        "description": "極系の敵がいるとき、2ターンの間、\n超系の味方全員のATK20%UP(1回のみ)",
        "support_film_id": 3,
        "cost": 70,
        "level": 3,
        "open_at": "",
        "link_id": 300013,
        "root_id": 30001
    },
    {
        "id": 30002,
        "name": "パラパラブラザーズ登場！",
        "description": "バトル開始から3ターン目以降に、\nHP88%以上のとき\n1ターンの間、\n敵全体の必殺技を封じる(1回のみ)",
        "support_film_id": 3,
        "cost": 120,
        "level": 1,
        "open_at": "",
        "link_id": 30002,
        "root_id": 30002
    },
    {
        "id": 30003,
        "name": "ブラのショッピング",
        "description": "特殊効果「追加ドロップ率UP」があるイベントで\n追加ドロップ率が85%UP(1回のみ)",
        "support_film_id": 3,
        "cost": 120,
        "level": 1,
        "open_at": "",
        "link_id": 30003,
        "root_id": 30003
    },
    {
        "id": 30004,
        "name": "心をひとつに！ピッコロとデンデ",
        "description": "バトル開始から3ターン目に、\n属性気玉のうちランダムで\n体気玉以外の1種類を体気玉に変化させ、\n2ターンの間「GT HERO」または\n「コンビネーション」カテゴリの\n味方全員の気力+2、ATKとDEF25%UP、\n1ターンの間超系の味方全員のATK10%UP(1回のみ)",
        "support_film_id": 3,
        "cost": 120,
        "level": 5,
        "open_at": "",
        "link_id": 300045,
        "root_id": 30004
    },
    {
        "id": 30005,
        "name": "悟空が子供に！？",
        "description": "バトル開始から3ターンの間、\n敵全体のATKとDEFを15%DOWNし、\n「孫悟空の系譜」カテゴリまたは\n「GT HERO」カテゴリの敵がいる場合、\n更に敵全体のATKとDEFを10%DOWNさせる(1回のみ)",
        "support_film_id": 3,
        "cost": 170,
        "level": 5,
        "open_at": "",
        "link_id": 300055,
        "root_id": 30005
    },
    {
        "id": 30006,
        "name": "さらば悟空！！",
        "description": "バトル中「GT HERO」カテゴリの\n味方全員のATKとDEF10%UPし、\nバトル開始から7ターンの間、\nチームの名称に「孫悟空」を含むキャラ\n(ギニュー、Jr.等を除く)の気力+1(1回のみ)",
        "support_film_id": 3,
        "cost": 200,
        "level": 1,
        "open_at": "",
        "link_id": 30006,
        "root_id": 30006
    },
    {
        "id": 30008,
        "name": "神龍が敵に？！",
        "description": "バトル中「邪悪龍編」カテゴリの\n味方全員の気力+1、ATKとDEF20%UPし、\nバトル開始から7ターンの間、\n「邪悪龍編」カテゴリの\n極系の味方全員の気力+2(1回のみ)",
        "support_film_id": 3,
        "cost": 200,
        "level": 3,
        "open_at": "",
        "link_id": 300083,
        "root_id": 30008
    },
    {
        "id": 30009,
        "name": "ピッコロの激励",
        "description": "HP59%以下で\nチームに「救世主」カテゴリの味方がいるとき、\n2ターンの間、味方全員の気力+3、\n更に超系の味方全員の気力+1(1回のみ)",
        "support_film_id": 3,
        "cost": 150,
        "level": 1,
        "open_at": "",
        "link_id": 30009,
        "root_id": 30009
    },
    {
        "id": 30010,
        "name": "パンのファーストキス",
        "description": "バトル開始から2ターンの間、\n「親友の絆」カテゴリの\n味方全員のATKとDEF10%UP(1回のみ)",
        "support_film_id": 3,
        "cost": 100,
        "level": 1,
        "open_at": "",
        "link_id": 30010,
        "root_id": 30010
    },
    {
        "id": 30011,
        "name": "思い出の写真",
        "description": "バトル開始から2ターンの間、\n「大猿パワー」カテゴリの味方全員の\n気力+1、ATKとDEF10%UP(1回のみ)",
        "support_film_id": 3,
        "cost": 100,
        "level": 1,
        "open_at": "",
        "link_id": 30011,
        "root_id": 30011
    },
    {
        "id": 30012,
        "name": "そして100年後…",
        "description": "バトル中「孫悟空の系譜」\nまたは「ベジータの系譜」カテゴリの\n味方全員のATKとDEF10%UP",
        "support_film_id": 3,
        "cost": 200,
        "level": 1,
        "open_at": "",
        "link_id": 30012,
        "root_id": 30012
    },
    {
        "id": 30013,
        "name": "余裕のゴジータ",
        "description": "バトル中「融合/合体戦士」カテゴリの\n味方全員のATKとDEF10%UPし、\nバトル開始から7ターンの間、\n「邪悪龍編」カテゴリの\n味方全員の気力+1(1回のみ)",
        "support_film_id": 3,
        "cost": 200,
        "level": 1,
        "open_at": "",
        "link_id": 30013,
        "root_id": 30013
    },
    {
        "id": 40001,
        "name": "初めてのてんぷら",
        "description": "バトル開始から3ターン目に、\n3ターンの間、味方全員の気力+3(1回のみ)",
        "support_film_id": 4,
        "cost": 70,
        "level": 3,
        "open_at": "",
        "link_id": 400013,
        "root_id": 40001
    },
    {
        "id": 40002,
        "name": "師弟の目指す先",
        "description": "バトル開始から3ターンの間、\n「師弟の絆」または「コンビネーション」カテゴリの\n味方全員の気力+1、ATKとDEF20%UP(1回のみ)",
        "support_film_id": 4,
        "cost": 100,
        "level": 5,
        "open_at": "",
        "link_id": 400025,
        "root_id": 40002
    },
    {
        "id": 40003,
        "name": "全王のありがたいお言葉",
        "description": "バトル中「宇宙サバイバル編」カテゴリの\n味方全員の気力+1、ATKとDEF20%UPし、\n「大会出場者」カテゴリを含む場合は\nバトル開始から7ターンの間、\n更に気力+2(1回のみ)",
        "support_film_id": 4,
        "cost": 200,
        "level": 3,
        "open_at": "",
        "link_id": 400033,
        "root_id": 40003
    },
    {
        "id": 40004,
        "name": "姉弟の絆",
        "description": "自身のHP50%以下の時、自身のHPが35%回復し、\n2ターンの間、「兄弟の絆」\nまたは「第7宇宙代表」カテゴリの\n味方全員の気力+1、ATKとDEF18%UP、\n会心の発動確率17%UP(1回のみ)",
        "support_film_id": 4,
        "cost": 100,
        "level": 5,
        "open_at": "",
        "link_id": 400045,
        "root_id": 40004
    },
    {
        "id": 40005,
        "name": "トランクスとマイの再会",
        "description": "バトル開始から3ターンの間、\nチームに「時空を超えし者」カテゴリの\n味方が2体以上いるとき\n味方全員の気力+1、ATKとDEF15%UPし、\n更に「時空を超えし者」カテゴリの\n味方全員のATKとDEF5%UP(1回のみ)",
        "support_film_id": 4,
        "cost": 120,
        "level": 5,
        "open_at": "",
        "link_id": 400055,
        "root_id": 40005
    },
    {
        "id": 40006,
        "name": "ブラ誕生！",
        "description": "バトル中「ベジータの系譜」カテゴリの\n味方全員の気力+1、ATKとDEF20%UPし、\n「親子の絆」カテゴリを含む場合は\nバトル開始から7ターンの間、\n更に気力+2(1回のみ)",
        "support_film_id": 4,
        "cost": 200,
        "level": 3,
        "open_at": "",
        "link_id": 400063,
        "root_id": 40006
    },
    {
        "id": 40007,
        "name": "ふたりのザマス",
        "description": "バトル中「世界の混乱」カテゴリの\n味方全員の気力+1、ATKとDEF20%UPし、\nバトル開始から7ターンの間、\nチームの名称に「ザマス」または\n「ゴクウブラック」を含む\nキャラの気力+2(1回のみ)",
        "support_film_id": 4,
        "cost": 200,
        "level": 3,
        "open_at": "",
        "link_id": 400073,
        "root_id": 40007
    },
    {
        "id": 40008,
        "name": "絶対神の嘆き",
        "description": "「時空を超えし者」または\n「融合/合体戦士」カテゴリの敵がいるとき、\n4ターンの間、「神次元」または\n「世界の混乱」カテゴリの\n味方全員の気力+2、ATKとDEF20%UP(1回のみ)",
        "support_film_id": 4,
        "cost": 120,
        "level": 5,
        "open_at": "",
        "link_id": 400085,
        "root_id": 40008
    },
    {
        "id": 40009,
        "name": "トランクスとマイの旅立ち",
        "description": "バトル中「未来編」カテゴリの\n味方全員のATKとDEF10%UPし、\nバトル開始から7ターンの間、\nチームの名称に\n「トランクス」(幼年期、GTを除く)または\n「マイ(未来)」を含むキャラの気力+1(1回のみ)",
        "support_film_id": 4,
        "cost": 200,
        "level": 1,
        "open_at": "",
        "link_id": 40009,
        "root_id": 40009
    },
    {
        "id": 40010,
        "name": "スーパーサタンの奇跡！？",
        "description": "「神次元」カテゴリまたは極系の敵がいるとき、\n4ターンの間、超系の味方全員の気力+5、\nATKとDEF10%UP、\n「救世主」または「地球を守りし英雄」カテゴリの\n味方全員のATKとDEF10%UP(1回のみ)",
        "support_film_id": 4,
        "cost": 150,
        "level": 5,
        "open_at": "",
        "link_id": 400105,
        "root_id": 40010
    },
    {
        "id": 40011,
        "name": "サイヤ人の終わりなき闘い",
        "description": "バトル中「超サイヤ人を超えた力」カテゴリの\n味方全員の気力+1、ATKとDEF20%UPし、\nバトル開始から7ターンの間、\n「純粋サイヤ人」カテゴリの\n味方全員の気力+1(1回のみ)",
        "support_film_id": 4,
        "cost": 200,
        "level": 3,
        "open_at": "",
        "link_id": 400113,
        "root_id": 40011
    },
    {
        "id": 40013,
        "name": "ふたりの全王",
        "description": "バトル中「時空を超えし者」カテゴリの\n味方全員のATKとDEF10%UPし、\nバトル開始から7ターンの間、\n「神次元」カテゴリの\n味方全員の気力+1(1回のみ)",
        "support_film_id": 4,
        "cost": 200,
        "level": 1,
        "open_at": "",
        "link_id": 40013,
        "root_id": 40013
    },
    {
        "id": 50001,
        "name": "飛ばせハイヤードラゴン！",
        "description": "HP70%以下のとき、自身のHPが15%回復し、\n1ターンの間、味方全員のATKとDEF15%UP(1回のみ)",
        "support_film_id": 5,
        "cost": 70,
        "level": 3,
        "open_at": "",
        "link_id": 500013,
        "root_id": 50001
    },
    {
        "id": 50002,
        "name": "クリリン大熱唱",
        "description": "バトル開始から3ターンの間、\n「願いの力」カテゴリの味方全員の\n気力+2、ATKとDEF8%UP、会心率3%UPし、\n敵全体のATKとDEFを\n1ターン目のみ10%DOWN、\n2ターン目のみ9%DOWN、\n3ターン目のみ8%DOWNさせる(1回のみ)",
        "support_film_id": 5,
        "cost": 120,
        "level": 5,
        "open_at": "",
        "link_id": 500025,
        "root_id": 50002
    },
    {
        "id": 50003,
        "name": "カカロット",
        "description": "バトル中「劇場版HERO」カテゴリの\n味方全員の気力+1、ATKとDEF20%UPし、\nバトル開始から7ターンの間、\nチームの名称に「孫悟空」を含むキャラ\n(ギニュー、Jr.等を除く)の気力+2(1回のみ)",
        "support_film_id": 5,
        "cost": 200,
        "level": 3,
        "open_at": "",
        "link_id": 500033,
        "root_id": 50003
    },
    {
        "id": 50004,
        "name": "神次元への好奇心",
        "description": "バトル開始から3ターンの間、\n「神次元」カテゴリの\n味方全員のATKとDEF25%UPし、\n「神次元」カテゴリまたは\n「劇場版BOSS」カテゴリの敵がいる場合、\n3ターンの間、味方全員の気力+2(1回のみ)",
        "support_film_id": 5,
        "cost": 120,
        "level": 5,
        "open_at": "",
        "link_id": 500045,
        "root_id": 50004
    },
    {
        "id": 50005,
        "name": "あの世からの一撃",
        "description": "バトル開始から5ターン目に、\n3ターンの間、味方全員のATKとDEF15%UPし、\nバトル開始から5ターン目以降に、\n「劇場版BOSS」または「宇宙をわたる戦士」\nカテゴリの敵がいるとき、\n2ターンの間、超系の味方全員のATKとDEF10%UP、\n1ターンの間、「あの世の戦士」カテゴリの\n味方全員のATK10%UP(1回のみ)",
        "support_film_id": 5,
        "cost": 120,
        "level": 5,
        "open_at": "",
        "link_id": 500055,
        "root_id": 50005
    },
    {
        "id": 50006,
        "name": "クウラの冷評",
        "description": "バトル中「最凶の一族」カテゴリの\n味方全員のATKとDEF10%UPし、\nバトル開始から7ターンの間、\nチームの名称に「クウラ」を含む\nキャラの気力+1(1回のみ)",
        "support_film_id": 5,
        "cost": 200,
        "level": 1,
        "open_at": "",
        "link_id": 50006,
        "root_id": 50006
    },
    {
        "id": 50007,
        "name": "残酷な挑発",
        "description": "バトル開始から3ターンの間、\n「恐怖の征服」または「最凶の一族」カテゴリの\n味方全員の気力+2、ATKとDEF20%UP(1回のみ)",
        "support_film_id": 5,
        "cost": 120,
        "level": 5,
        "open_at": "",
        "link_id": 500075,
        "root_id": 50007
    },
    {
        "id": 50008,
        "name": "悟飯を救え！",
        "description": "バトル開始から4ターン目以降、\nHPが58%以下のとき、\n1ターンの間、超系の味方全員の\nATKとDEF20%UPし、\nチームに「救世主」カテゴリの味方がいるとき\n自身のHPが10%回復する(1回のみ)",
        "support_film_id": 5,
        "cost": 150,
        "level": 1,
        "open_at": "",
        "link_id": 50008,
        "root_id": 50008
    },
    {
        "id": 50009,
        "name": "悟飯の心",
        "description": "バトル開始から3ターン目以降、\nHPが58%以下のとき、\n2ターンの間、「混血サイヤ人」カテゴリの\n味方全員のATKとDEF20%UP、\n「大猿パワー」カテゴリの\n味方全員の気力+2(1回のみ)",
        "support_film_id": 5,
        "cost": 150,
        "level": 1,
        "open_at": "",
        "link_id": 50009,
        "root_id": 50009
    },
    {
        "id": 50010,
        "name": "勇者からの贈り物",
        "description": "バトル開始から2ターンの間、\n「語り継がれし者」カテゴリの\n味方全員のATKとDEF10%UP(1回のみ)",
        "support_film_id": 5,
        "cost": 100,
        "level": 1,
        "open_at": "",
        "link_id": 50010,
        "root_id": 50010
    },
    {
        "id": 50011,
        "name": "破壊神のプライド",
        "description": "バトル中「神次元」カテゴリの\n味方全員のATKとDEF10%UPし、\nバトル開始から7ターンの間、\n「惑星破壊」カテゴリの\n味方全員の気力+1(1回のみ)",
        "support_film_id": 5,
        "cost": 200,
        "level": 1,
        "open_at": "",
        "link_id": 50011,
        "root_id": 50011
    },
    {
        "id": 50012,
        "name": "散りゆくスーパーヒーロー",
        "description": "バトル中「超HERO」カテゴリの\n味方全員のATKとDEF10%UPし、\nチームに名称に「ガンマ」を含むキャラがいるとき\nバトル開始から7ターンの間、\n味方全員の気力+2(1回のみ)",
        "support_film_id": 5,
        "cost": 200,
        "level": 1,
        "open_at": "",
        "link_id": 50012,
        "root_id": 50012
    },
    {
        "id": 50013,
        "name": "地球の地獄",
        "description": "バトル開始から4ターン目以降、2ターンの間、\n「劇場版BOSS」または「あの世の戦士」\nカテゴリの敵全体のATK10%DOWN(1回のみ)",
        "support_film_id": 5,
        "cost": 100,
        "level": 1,
        "open_at": "",
        "link_id": 50013,
        "root_id": 50013
    },
    {
        "id": 50014,
        "name": "悟空とチチの面接",
        "description": "バトル中「親子の絆」カテゴリの\n味方全員のATKとDEF10%UPし、\nバトル開始から7ターンの間、\nチームの名称に\n「孫悟飯(じいちゃん、寄生等を除く)」を\n含むキャラの気力+1(1回のみ)",
        "support_film_id": 5,
        "cost": 200,
        "level": 1,
        "open_at": "",
        "link_id": 50014,
        "root_id": 50014
    },
    {
        "id": 50015,
        "name": "ブロリーの潜在パワー",
        "description": "バトル中「劇場版BOSS」\nまたは「リベンジ」カテゴリの\n味方全員のATKとDEF10%UPし、\nバトル開始から7ターンの間、\nチームの名称に「ブロリー」\nまたは「パラガス」を含む\nキャラの気力+1(1回のみ)",
        "support_film_id": 5,
        "cost": 200,
        "level": 1,
        "open_at": "",
        "link_id": 50015,
        "root_id": 50015
    },
    {
        "id": 50016,
        "name": "18号からの請求",
        "description": "特殊効果「追加ドロップ率UP」があるイベントで\n追加ドロップ率が120%UP(1回のみ)",
        "support_film_id": 5,
        "cost": 120,
        "level": 3,
        "open_at": "",
        "link_id": 500163,
        "root_id": 50016
    },
    {
        "id": 50017,
        "name": "強くてやさしいお父さん",
        "description": "HP50%以下で\nチームに「託された意志」カテゴリの味方がいるとき、\n2ターンの間、味方全員のATKとDEF15%UP(1回のみ)",
        "support_film_id": 5,
        "cost": 120,
        "level": 1,
        "open_at": "",
        "link_id": 50017,
        "root_id": 50017
    },
    {
        "id": 50020,
        "name": "サンキュー",
        "description": "バトル中「天才戦士」\nまたは「純粋サイヤ人」カテゴリの\n味方全員のATKとDEF10%UP",
        "support_film_id": 5,
        "cost": 200,
        "level": 1,
        "open_at": "",
        "link_id": 50020,
        "root_id": 50020
    },
    {
        "id": 50021,
        "name": "空を飛ぶパン",
        "description": "バトル開始から3ターン目以降、\n「師弟の絆」カテゴリのキャラが\nチームにいるとき、\n3ターンの間、味方全員の\nATKとDEFと会心率5%UP(1回のみ)",
        "support_film_id": 5,
        "cost": 100,
        "level": 1,
        "open_at": "",
        "link_id": 50021,
        "root_id": 50021
    }
]